# .samantha.yml - Samantha Security Configuration

version: 1

# ==============================================
# VULNERABILITY SCANNING
# ==============================================
scanning:
  # Dependency scanning
  dependencies:
    enabled: true
    failOn: 'high'  # low | medium | high | critical
    ignoreDevDependencies: false
    autoFix: false
    
  # Secret detection
  secrets:
    enabled: true
    failOnDetection: true
    patterns:
      # AWS
      - name: 'aws_access_key'
        pattern: 'AKIA[0-9A-Z]{16}'
      - name: 'aws_secret_key'
        pattern: '[0-9a-zA-Z/+]{40}'
      # GitHub
      - name: 'github_token'
        pattern: 'gh[ps]_[0-9a-zA-Z]{36}'
      # Private Keys
      - name: 'private_key'
        pattern: '-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----'
      # Generic
      - name: 'generic_secret'
        pattern: '(?i)(password|secret|token|api_key)\s*[:=]\s*["\'][^"\']{8,}["\']'
        
    excludePaths:
      - '**/*.test.ts'
      - '**/*.spec.ts'
      - '**/test/**'
      - '**/fixtures/**'
      - '**/mocks/**'
      - '**/__tests__/**'
      
  # Static Application Security Testing
  sast:
    enabled: true
    rules:
      - 'owasp-top-ten'
      - 'security-audit'
      - 'secrets'
    excludeRules: []
    
  # Container scanning
  container:
    enabled: true
    failOn: 'high'
    scanBaseImage: true

# ==============================================
# AUTHENTICATION
# ==============================================
authentication:
  # Password policy (NIST 800-63B compliant)
  password:
    minLength: 12
    maxLength: 128
    requireBreachCheck: true
    noComplexityRequirements: true  # Per NIST guidelines
    noPeriodicRotation: true        # Per NIST guidelines
    
  # Password hashing
  hashing:
    algorithm: 'argon2id'  # argon2id | bcrypt | scrypt
    # Argon2id settings
    argon2:
      memoryCost: 65536  # 64 MB
      timeCost: 3
      parallelism: 4
    # bcrypt settings
    bcrypt:
      rounds: 12
      
  # Session management
  session:
    cookieSecure: true
    cookieHttpOnly: true
    cookieSameSite: 'strict'  # strict | lax | none
    absoluteTimeout: 86400     # 24 hours
    idleTimeout: 3600          # 1 hour
    regenerateOnLogin: true
    
  # Multi-factor authentication
  mfa:
    enabled: true
    requiredForAdmin: true
    requiredForAll: false
    methods:
      - 'totp'
      - 'webauthn'
    recoveryCodesCount: 10
    
  # Rate limiting
  rateLimit:
    login:
      maxAttempts: 5
      windowMinutes: 15
      lockoutMinutes: 30
    passwordReset:
      maxAttempts: 3
      windowMinutes: 60
    api:
      maxRequests: 100
      windowMinutes: 1

# ==============================================
# AUTHORIZATION
# ==============================================
authorization:
  model: 'rbac'  # rbac | abac
  denyByDefault: true
  checkOnEveryRequest: true
  logDenials: true

# ==============================================
# DATA PROTECTION
# ==============================================
dataProtection:
  # Data classification
  classification:
    restricted:
      - 'password'
      - 'ssn'
      - 'creditCardNumber'
      - 'cvv'
      - 'authToken'
      - 'apiKey'
    confidential:
      - 'email'
      - 'phone'
      - 'address'
      - 'dateOfBirth'
      - 'salary'
    internal:
      - 'userId'
      - 'accountId'
      - 'orderId'
      
  # Encryption
  encryption:
    atRest:
      enabled: true
      algorithm: 'aes-256-gcm'
    inTransit:
      enabled: true
      minTlsVersion: '1.2'
    fieldLevel:
      enabled: false
      fields: []
      
  # Key management
  keyManagement:
    provider: 'env'  # env | aws-kms | gcp-kms | azure-keyvault | hashicorp-vault
    rotationDays: 365
    
  # Data retention
  retention:
    defaultDays: 365
    piiDays: 90
    auditLogDays: 2555  # 7 years
    
  # Masking for logs/display
  masking:
    email: true        # j***@example.com
    phone: true        # ***-***-1234
    creditCard: true   # ****-****-****-1234

# ==============================================
# SECURITY HEADERS
# ==============================================
headers:
  # Content Security Policy
  contentSecurityPolicy:
    enabled: true
    directives:
      defaultSrc: ["'self'"]
      scriptSrc: ["'self'"]
      styleSrc: ["'self'", "'unsafe-inline'"]
      imgSrc: ["'self'", 'data:', 'https:']
      fontSrc: ["'self'"]
      connectSrc: ["'self'"]
      frameSrc: ["'none'"]
      objectSrc: ["'none'"]
      baseUri: ["'self'"]
      formAction: ["'self'"]
      frameAncestors: ["'none'"]
      upgradeInsecureRequests: true
      
  # HTTP Strict Transport Security
  hsts:
    enabled: true
    maxAge: 31536000  # 1 year
    includeSubDomains: true
    preload: true
    
  # Other headers
  xFrameOptions: 'DENY'
  xContentTypeOptions: 'nosniff'
  xXssProtection: '1; mode=block'
  referrerPolicy: 'strict-origin-when-cross-origin'
  
  # Permissions Policy
  permissionsPolicy:
    accelerometer: []
    camera: []
    geolocation: []
    gyroscope: []
    magnetometer: []
    microphone: []
    payment: []
    usb: []

# ==============================================
# INPUT VALIDATION
# ==============================================
inputValidation:
  # Global validation rules
  maxRequestSize: '1mb'
  maxUrlLength: 2048
  maxHeaderSize: 8192
  
  # SQL injection prevention
  sqlInjection:
    requireParameterizedQueries: true
    detectPatterns: true
    
  # XSS prevention
  xss:
    sanitizeHtml: true
    escapeOutput: true
    allowedTags: ['b', 'i', 'em', 'strong', 'a', 'p', 'br']
    
  # File upload
  fileUpload:
    maxSize: '10mb'
    allowedTypes:
      - 'image/jpeg'
      - 'image/png'
      - 'image/gif'
      - 'application/pdf'
    validateContent: true
    quarantinePath: '/tmp/quarantine'

# ==============================================
# AUDIT LOGGING
# ==============================================
auditLog:
  enabled: true
  
  # Events to log
  events:
    authentication:
      - 'login.success'
      - 'login.failure'
      - 'logout'
      - 'password.change'
      - 'password.reset'
      - 'mfa.enable'
      - 'mfa.disable'
    authorization:
      - 'permission.denied'
      - 'role.assign'
      - 'role.remove'
    data:
      - 'create'
      - 'update'
      - 'delete'
      - 'export'
      - 'bulk'
    admin:
      - 'user.create'
      - 'user.delete'
      - 'user.suspend'
      - 'settings.change'
    security:
      - 'suspicious.activity'
      - 'rate.limit.exceeded'
      - 'breach.detected'
      
  # What NOT to log
  excludeFields:
    - 'password'
    - 'token'
    - 'secret'
    - 'creditCard'
    - 'ssn'
    
  # Storage
  storage:
    type: 'database'  # database | file | cloudwatch | elasticsearch
    retention: 2555   # 7 years
    immutable: true

# ==============================================
# COMPLIANCE
# ==============================================
compliance:
  frameworks:
    gdpr:
      enabled: true
      dataSubjectRights: true
      consentManagement: true
      breachNotification: true
    soc2:
      enabled: true
      trustPrinciples:
        - 'security'
        - 'availability'
        - 'confidentiality'
    pciDss:
      enabled: false
    hipaa:
      enabled: false

# ==============================================
# ALERTING
# ==============================================
alerting:
  enabled: true
  
  channels:
    - type: 'slack'
      webhook: '${SECURITY_SLACK_WEBHOOK}'
      severity: ['critical', 'high']
    - type: 'email'
      recipients: ['security@company.com']
      severity: ['critical']
    - type: 'pagerduty'
      routingKey: '${PAGERDUTY_SECURITY_KEY}'
      severity: ['critical']
      
  thresholds:
    failedLogins:
      count: 10
      windowMinutes: 5
      severity: 'high'
    suspiciousActivity:
      count: 5
      windowMinutes: 10
      severity: 'high'
    dependencyVulnerability:
      severity: 'critical'
      immediate: true

# ==============================================
# CI/CD INTEGRATION
# ==============================================
cicd:
  # Security gates
  gates:
    preScan: true
    blockOnCritical: true
    blockOnHigh: false
    requireApprovalForOverride: true
    
  # Allowed overrides (with justification)
  allowedOverrides:
    - 'known-false-positive'
    - 'accepted-risk'
    - 'pending-fix'
