# .ana.yml - Ana Analytics Configuration

version: 1

# ==============================================
# THEME CONFIGURATION
# ==============================================
theme:
  # Brand colors
  colors:
    primary: '#2563EB'
    secondary: '#7C3AED'
    accent: '#DB2777'
    
    # Status colors
    success: '#16A34A'
    warning: '#EAB308'
    error: '#DC2626'
    neutral: '#6B7280'
    
    # Background colors
    background:
      light: '#FFFFFF'
      subtle: '#F9FAFB'
      dark: '#111827'
      
    # Text colors
    text:
      primary: '#111827'
      secondary: '#6B7280'
      muted: '#9CA3AF'
      inverse: '#FFFFFF'
      
  # Categorical palette (for distinct categories)
  categorical:
    - '#2563EB'  # Blue
    - '#7C3AED'  # Purple
    - '#DB2777'  # Pink
    - '#EA580C'  # Orange
    - '#16A34A'  # Green
    - '#0891B2'  # Cyan
    - '#4F46E5'  # Indigo
    - '#BE185D'  # Rose
    - '#C2410C'  # Deep Orange
    - '#15803D'  # Deep Green
    
  # Sequential palettes (for continuous data)
  sequential:
    blue:
      - '#EFF6FF'
      - '#DBEAFE'
      - '#BFDBFE'
      - '#93C5FD'
      - '#60A5FA'
      - '#3B82F6'
      - '#2563EB'
      - '#1D4ED8'
      - '#1E40AF'
    green:
      - '#F0FDF4'
      - '#DCFCE7'
      - '#BBF7D0'
      - '#86EFAC'
      - '#4ADE80'
      - '#22C55E'
      - '#16A34A'
      - '#15803D'
      - '#166534'
      
  # Diverging palette (for data with meaningful midpoint)
  diverging:
    redBlue:
      - '#DC2626'
      - '#EF4444'
      - '#FCA5A5'
      - '#FECACA'
      - '#F5F5F5'
      - '#BFDBFE'
      - '#93C5FD'
      - '#3B82F6'
      - '#2563EB'
      
  # Typography
  fonts:
    family: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
    mono: "'JetBrains Mono', 'Fira Code', monospace"
    
    sizes:
      title: '18px'
      subtitle: '14px'
      body: '13px'
      label: '12px'
      caption: '11px'
      
  # Dark mode
  darkMode:
    enabled: true
    default: false
    colors:
      background: '#111827'
      surface: '#1F2937'
      text: '#F9FAFB'

# ==============================================
# CHART DEFAULTS
# ==============================================
charts:
  # Animation
  animation:
    enabled: true
    duration: 300
    easing: 'easeInOutQuart'
    
  # Tooltip
  tooltip:
    enabled: true
    backgroundColor: '#1F2937'
    textColor: '#F9FAFB'
    borderRadius: 8
    padding: 12
    shadow: true
    
  # Legend
  legend:
    position: 'bottom'  # top | bottom | left | right
    align: 'center'
    
  # Grid
  grid:
    show: true
    color: '#E5E7EB'
    strokeDasharray: '4 4'
    
  # Axis
  axis:
    color: '#9CA3AF'
    tickColor: '#E5E7EB'
    labelColor: '#6B7280'
    
  # Responsive breakpoints
  responsive:
    enabled: true
    breakpoints:
      mobile: 480
      tablet: 768
      desktop: 1024
      wide: 1440
      
  # Default dimensions
  dimensions:
    minHeight: 200
    aspectRatio: 1.618  # Golden ratio

# ==============================================
# KPI CARD DEFAULTS
# ==============================================
kpi:
  # Trend indicator
  trend:
    showArrow: true
    showPercentage: true
    positiveColor: '#16A34A'
    negativeColor: '#DC2626'
    neutralColor: '#6B7280'
    
  # Sparkline
  sparkline:
    show: true
    height: 40
    color: '#3B82F6'
    
  # Comparison
  comparison:
    showPreviousPeriod: true
    showGoal: true

# ==============================================
# DASHBOARD DEFAULTS
# ==============================================
dashboard:
  # Layout
  layout:
    columns: 12
    rowHeight: 100
    gap: 16
    padding: 24
    
  # Widgets
  widgets:
    defaultSizes:
      kpi: { w: 3, h: 1 }
      lineChart: { w: 6, h: 3 }
      barChart: { w: 6, h: 3 }
      pieChart: { w: 4, h: 3 }
      table: { w: 12, h: 4 }
      
  # Filters
  filters:
    position: 'top'  # top | sidebar
    dateRangeDefault: '30d'
    dateRangeOptions:
      - label: 'Today'
        value: 'today'
      - label: 'Yesterday'
        value: 'yesterday'
      - label: 'Last 7 days'
        value: '7d'
      - label: 'Last 30 days'
        value: '30d'
      - label: 'Last 90 days'
        value: '90d'
      - label: 'This month'
        value: 'this_month'
      - label: 'Last month'
        value: 'last_month'
      - label: 'This year'
        value: 'this_year'
      - label: 'Custom'
        value: 'custom'
        
  # Refresh
  refresh:
    autoRefresh: false
    interval: 300  # seconds
    showLastUpdated: true

# ==============================================
# DATA CONFIGURATION
# ==============================================
data:
  # Timezone
  timezone: 'UTC'
  
  # Date format
  dateFormat: 'MMM d, yyyy'
  timeFormat: 'h:mm a'
  dateTimeFormat: 'MMM d, yyyy h:mm a'
  
  # Number formatting
  numbers:
    locale: 'en-US'
    
    # Formatting rules
    formats:
      number: { maximumFractionDigits: 2 }
      currency: { style: 'currency', currency: 'USD' }
      percent: { style: 'percent', maximumFractionDigits: 1 }
      compact: { notation: 'compact' }
      
  # Null handling
  nullValue: 'N/A'
  emptyValue: '—'
  
  # Caching
  cache:
    enabled: true
    ttlSeconds: 300
    maxSize: 100

# ==============================================
# EXPORT OPTIONS
# ==============================================
export:
  # Available formats
  formats:
    csv:
      enabled: true
      delimiter: ','
      includeHeaders: true
    xlsx:
      enabled: true
      sheetName: 'Data'
    pdf:
      enabled: true
      orientation: 'landscape'
      pageSize: 'A4'
    png:
      enabled: true
      scale: 2
      
  # Branding
  branding:
    enabled: true
    logo: '/assets/logo.png'
    footer: 'Generated by Analytics'
    
  # Scheduling
  scheduling:
    enabled: true
    formats: ['pdf', 'csv']
    frequencies:
      - daily
      - weekly
      - monthly

# ==============================================
# EMBEDDED ANALYTICS
# ==============================================
embedded:
  enabled: true
  
  # Authentication
  auth:
    type: 'jwt'  # jwt | apiKey | session
    tokenExpiry: 3600  # seconds
    
  # Row-level security
  security:
    enabled: true
    customerIdField: 'customer_id'
    enforceFilters: true
    
  # Theming
  theming:
    allowCustomThemes: true
    inheritParentStyles: true
    
  # Features by tier
  tiers:
    basic:
      features:
        - prebuiltDashboards
        - csvExport
        - dateRangeFilter
      customization: false
      apiAccess: false
      
    pro:
      features:
        - prebuiltDashboards
        - csvExport
        - xlsxExport
        - customDateRanges
        - periodComparison
        - scheduledReports
        - chartCustomization
      customization: true
      apiAccess: false
      
    enterprise:
      features:
        - customDashboards
        - allExportFormats
        - apiAccess
        - whiteLabel
        - realTimeData
        - customMetrics
        - webhooks
      customization: true
      apiAccess: true

# ==============================================
# ACCESSIBILITY
# ==============================================
accessibility:
  # WCAG level
  wcagLevel: 'AA'  # A | AA | AAA
  
  # Requirements
  requirements:
    minContrastRatio: 4.5
    focusIndicators: true
    keyboardNavigation: true
    screenReaderSupport: true
    
  # Color blindness
  colorBlindness:
    safeMode: false  # When true, uses colorblind-safe palette
    patterns: true   # Use patterns in addition to colors

# ==============================================
# PERFORMANCE
# ==============================================
performance:
  # Data limits
  limits:
    maxDataPoints: 10000
    maxCategories: 100
    tablePageSize: 50
    
  # Sampling
  sampling:
    enabled: true
    threshold: 5000
    method: 'random'  # random | systematic | stratified
    
  # Lazy loading
  lazyLoad:
    enabled: true
    threshold: 'viewport'
    
  # Virtualization
  virtualization:
    enabled: true
    overscan: 5
