# .isabel.yml - Isabel Infrastructure Configuration

version: 1

# ==============================================
# PROJECT
# ==============================================
project:
  name: "{{PROJECT_NAME}}"
  organization: "{{ORGANIZATION}}"

# ==============================================
# CLOUD PROVIDER
# ==============================================
provider:
  name: aws  # aws | gcp | azure
  
  # Primary region
  region: us-east-1
  
  # Multi-region configuration
  regions:
    primary: us-east-1
    secondary: us-west-2
    
  # Account configuration
  account:
    id: "{{AWS_ACCOUNT_ID}}"
    alias: "{{ACCOUNT_ALIAS}}"

# ==============================================
# TERRAFORM CONFIGURATION
# ==============================================
terraform:
  # Version constraint
  version: ">= 1.5.0"
  
  # State backend
  backend:
    type: s3
    config:
      bucket: "${project.name}-terraform-state"
      key: "${environment}/terraform.tfstate"
      region: us-east-1
      encrypt: true
      dynamodb_table: "${project.name}-terraform-locks"
      
  # Provider versions
  providers:
    aws: "~> 5.0"
    kubernetes: "~> 2.23"
    helm: "~> 2.11"
    
  # Module sources
  modules:
    vpc: "terraform-aws-modules/vpc/aws"
    eks: "terraform-aws-modules/eks/aws"
    rds: "terraform-aws-modules/rds/aws"
    
  # Workspace configuration
  workspaces:
    enabled: true
    prefix: "${project.name}-"

# ==============================================
# NETWORKING
# ==============================================
networking:
  # VPC configuration
  vpc:
    cidr: "10.0.0.0/16"
    azCount: 3
    
    # Subnet configuration
    subnets:
      public:
        newbits: 4  # /20 subnets
        tags:
          "kubernetes.io/role/elb": "1"
      private:
        newbits: 4
        tags:
          "kubernetes.io/role/internal-elb": "1"
      database:
        newbits: 4
        
    # NAT Gateway
    natGateway:
      enabled: true
      singleNatGateway: false  # One per AZ for HA
      
    # VPC Flow Logs
    flowLogs:
      enabled: true
      destination: cloudwatch
      retentionDays: 30
      
  # DNS configuration
  dns:
    hostedZone: "{{DOMAIN}}"
    createPrivateZone: true
    
  # VPC Endpoints
  endpoints:
    gateway:
      - s3
      - dynamodb
    interface:
      - ecr.api
      - ecr.dkr
      - ec2
      - sts
      - logs
      - ssm
      - secretsmanager

# ==============================================
# KUBERNETES (EKS)
# ==============================================
kubernetes:
  # Cluster configuration
  cluster:
    version: "1.29"
    name: "${project.name}-${environment}"
    
    # API access
    endpointAccess:
      public: true
      private: true
      publicCidrs: []  # Empty = allow all
      
    # Logging
    logging:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
      
    # Encryption
    encryption:
      enabled: true
      resources:
        - secrets
        
  # Node groups
  nodeGroups:
    # System components (CoreDNS, etc.)
    system:
      instanceTypes:
        - t3.medium
      capacityType: ON_DEMAND
      scaling:
        minSize: 2
        maxSize: 4
        desiredSize: 2
      labels:
        role: system
      taints: []
      
    # General workloads
    general:
      instanceTypes:
        - m5.large
        - m5.xlarge
      capacityType: SPOT
      spotAllocationStrategy: capacity-optimized
      scaling:
        minSize: 2
        maxSize: 20
        desiredSize: 3
      labels:
        role: general
        
    # Compute-intensive workloads
    compute:
      instanceTypes:
        - c5.xlarge
        - c5.2xlarge
      capacityType: SPOT
      scaling:
        minSize: 0
        maxSize: 10
        desiredSize: 0
      labels:
        role: compute
      taints:
        - key: workload
          value: compute
          effect: NoSchedule
          
    # Memory-intensive workloads
    memory:
      instanceTypes:
        - r5.large
        - r5.xlarge
      capacityType: ON_DEMAND
      scaling:
        minSize: 0
        maxSize: 5
        desiredSize: 0
      labels:
        role: memory
        
  # Addons
  addons:
    coreDns:
      version: latest
    kubeProxy:
      version: latest
    vpcCni:
      version: latest
      config:
        enableNetworkPolicy: true
    ebsCsiDriver:
      version: latest
      
  # Additional controllers
  controllers:
    clusterAutoscaler:
      enabled: true
      version: "9.29.0"
    awsLoadBalancerController:
      enabled: true
      version: "1.6.0"
    externalDns:
      enabled: true
      version: "1.13.0"
    certManager:
      enabled: true
      version: "1.13.0"
    metricsServer:
      enabled: true
      version: "3.11.0"

# ==============================================
# DATABASE
# ==============================================
database:
  # RDS configuration
  rds:
    engine: postgres
    version: "15.4"
    
    # Instance configuration
    instance:
      class: db.r5.large
      multiAz: true
      
    # Storage
    storage:
      type: gp3
      allocated: 100
      maxAllocated: 500
      iops: 3000
      
    # Backup
    backup:
      retentionDays: 30
      window: "03:00-04:00"
      crossRegion: true
      
    # Maintenance
    maintenance:
      window: "Mon:04:00-Mon:05:00"
      autoMinorVersionUpgrade: true
      
    # Encryption
    encryption:
      enabled: true
      
    # Performance Insights
    performanceInsights:
      enabled: true
      retentionPeriod: 7

# ==============================================
# CACHING
# ==============================================
caching:
  elasticache:
    engine: redis
    version: "7.0"
    
    # Cluster mode
    clusterMode:
      enabled: true
      numShards: 2
      replicasPerShard: 1
      
    # Node configuration
    node:
      type: cache.r5.large
      
    # Encryption
    encryption:
      atRest: true
      inTransit: true
      
    # Backup
    backup:
      retentionDays: 7
      window: "03:00-04:00"

# ==============================================
# STORAGE
# ==============================================
storage:
  # S3 buckets
  s3:
    buckets:
      assets:
        versioning: true
        encryption: AES256
        lifecycle:
          - id: transition-to-ia
            transition:
              days: 30
              storageClass: STANDARD_IA
          - id: transition-to-glacier
            transition:
              days: 90
              storageClass: GLACIER
              
      logs:
        versioning: false
        encryption: AES256
        lifecycle:
          - id: expire-old-logs
            expiration:
              days: 90
              
      backups:
        versioning: true
        encryption: aws:kms
        replication:
          enabled: true
          destinationRegion: us-west-2

# ==============================================
# MONITORING
# ==============================================
monitoring:
  # CloudWatch
  cloudwatch:
    dashboards:
      - infrastructure
      - application
      - costs
      
    alarms:
      cpu:
        threshold: 80
        evaluationPeriods: 3
      memory:
        threshold: 85
        evaluationPeriods: 3
      disk:
        threshold: 80
        evaluationPeriods: 2
        
  # Prometheus / Grafana
  prometheus:
    enabled: true
    retention: 15d
    storage: 50Gi
    
  grafana:
    enabled: true
    adminPassword: "${GRAFANA_ADMIN_PASSWORD}"
    dashboards:
      - kubernetes
      - node-exporter
      - nginx-ingress

# ==============================================
# SECURITY
# ==============================================
security:
  # IAM
  iam:
    # IRSA (IAM Roles for Service Accounts)
    serviceAccounts:
      - name: aws-load-balancer-controller
        namespace: kube-system
        policyArns:
          - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      - name: external-dns
        namespace: kube-system
        policyArns:
          - arn:aws:iam::aws:policy/Route53FullAccess
          
  # KMS
  kms:
    keyRotation: true
    deletionWindow: 30
    
  # WAF
  waf:
    enabled: true
    rules:
      - AWSManagedRulesCommonRuleSet
      - AWSManagedRulesKnownBadInputsRuleSet
      - AWSManagedRulesSQLiRuleSet
      
  # GuardDuty
  guardduty:
    enabled: true
    
  # Security Hub
  securityHub:
    enabled: true
    standards:
      - AWS Foundational Security Best Practices
      - CIS AWS Foundations Benchmark

# ==============================================
# COST MANAGEMENT
# ==============================================
cost:
  # Budget
  budget:
    monthly:
      development: 1000
      staging: 2000
      production: 10000
    alertThresholds:
      - 50
      - 80
      - 100
    notifications:
      - email: devops@company.com
      - slack: "#cost-alerts"
      
  # Tagging
  tags:
    required:
      - Environment
      - Service
      - Team
      - ManagedBy
    defaults:
      ManagedBy: terraform
      Project: "${project.name}"
      
  # Cost allocation
  costAllocation:
    tags:
      - Environment
      - Service
      - Team

# ==============================================
# DISASTER RECOVERY
# ==============================================
dr:
  # Strategy
  strategy: warm-standby  # backup-restore | pilot-light | warm-standby | active-active
  
  # Targets
  rto: 30  # minutes
  rpo: 5   # minutes
  
  # Backup region
  backupRegion: us-west-2
  
  # Components
  components:
    database:
      replication: async
      backupFrequency: hourly
    storage:
      replication: async
      versioningEnabled: true
    secrets:
      replication: sync

# ==============================================
# ENVIRONMENTS
# ==============================================
environments:
  development:
    shortName: dev
    
    # Scaling
    kubernetes:
      nodeGroups:
        general:
          minSize: 1
          maxSize: 3
          
    # Cost optimization
    scheduling:
      enabled: true
      start: "0 8 * * 1-5"   # 8 AM weekdays
      stop: "0 20 * * 1-5"   # 8 PM weekdays
      timezone: America/New_York
      
    # Reduced redundancy
    database:
      multiAz: false
      instanceClass: db.t3.medium
      
  staging:
    shortName: stg
    
    kubernetes:
      nodeGroups:
        general:
          minSize: 2
          maxSize: 5
          
    database:
      multiAz: true
      instanceClass: db.r5.large
      
  production:
    shortName: prd
    
    kubernetes:
      nodeGroups:
        general:
          minSize: 3
          maxSize: 20
          
    database:
      multiAz: true
      instanceClass: db.r5.large
      readReplicas: 1
      
    # Full DR
    dr:
      enabled: true
