# .peter.yml - Peter Product Manager Configuration

version: 1

# ==============================================
# INPUT SOURCES
# ==============================================
inputs:
  # Sales requests
  sales:
    enabled: true
    sla_acknowledge: 24h       # Time to acknowledge
    sla_decision: 14d          # Time to prioritization decision
    channels:
      - type: slack
        channel: '#sales-requests'
      - type: email
        address: 'product-requests@company.com'
    required_fields:
      - deal_name
      - deal_value
      - customer_name
      - requested_feature
      - business_justification
      - requested_timeline

  # Customer feedback
  customers:
    enabled: true
    sla_acknowledge: 48h
    sla_decision: 21d
    sources:
      - type: feedback_widget
      - type: email
        address: 'feedback@company.com'
      - type: nps_followup
      - type: user_interviews
    required_fields:
      - customer_id
      - feedback_type        # feature_request | bug | improvement
      - description
      - use_case

  # Support tickets
  support:
    enabled: true
    sla_review: 7d
    sources:
      - type: zendesk
        view: 'feature-requests'
      - type: intercom
        tag: 'product-feedback'
    pattern_threshold: 5      # Create insight after N similar tickets
    auto_categorize: true

  # Developer suggestions
  developers:
    enabled: true
    sla_acknowledge: 72h
    channels:
      - type: slack
        channel: '#product-ideas'
      - type: github
        label: 'product-request'
    categories:
      - tech_debt
      - performance
      - security
      - dx_improvement
      - architecture

  # Customer success insights
  customer_success:
    enabled: true
    sla_acknowledge: 48h
    channels:
      - type: slack
        channel: '#cs-product-insights'
    insight_types:
      - churn_risk
      - expansion_blocker
      - adoption_barrier
      - success_pattern

# ==============================================
# PRIORITIZATION
# ==============================================
prioritization:
  # Primary framework
  framework: 'rice'
  
  # RICE configuration
  rice:
    # Impact scale
    impact_scale:
      massive: 3
      high: 2
      medium: 1
      low: 0.5
      minimal: 0.25
    
    # Confidence levels
    confidence_levels:
      high: 1.0           # Strong data
      medium: 0.8         # Some data
      low: 0.5            # Educated guess

  # Additional scoring factors
  factors:
    strategic_alignment:
      weight: 0.25
      scores:
        core_to_vision: 3
        supports_vision: 2
        neutral: 1
        tangential: 0.5
    
    customer_impact:
      weight: 0.25
      scores:
        critical_blocker: 3
        significant_improvement: 2
        nice_to_have: 1
        minimal: 0.5
    
    revenue_impact:
      weight: 0.20
      tiers:
        - min_arr: 500000
          score: 3
        - min_arr: 100000
          score: 2
        - min_arr: 25000
          score: 1
        - min_arr: 0
          score: 0.5

  # Priority thresholds
  thresholds:
    p0_critical: 800      # Drop everything
    p1_high: 500          # This quarter
    p2_medium: 300        # Next quarter
    p3_low: 100           # Backlog
    auto_decline: 50      # Below this, decline with explanation

  # MoSCoW defaults per priority
  moscow_mapping:
    p0: 'must_have'
    p1: 'should_have'
    p2: 'could_have'
    p3: 'wont_have'

# ==============================================
# DOCUMENTATION
# ==============================================
documentation:
  # Template locations
  templates:
    prd: 'templates/prd.md'
    user_story: 'templates/user-story.md'
    epic: 'templates/epic.md'
    feature_request: 'templates/feature-request.md'
    roadmap_item: 'templates/roadmap-item.md'

  # Required sections per document type
  required_sections:
    prd:
      - problem_statement
      - goals_and_nongoals
      - success_metrics
      - user_stories
      - acceptance_criteria
      - technical_considerations
      - risks_and_mitigations
    
    user_story:
      - story_format
      - acceptance_criteria
      - edge_cases
      - out_of_scope

  # Output locations
  output:
    prds: 'docs/internal/requirements/prds/'
    stories: 'docs/internal/requirements/stories/'
    epics: 'docs/internal/requirements/epics/'
    roadmap: 'docs/internal/roadmap/'

# ==============================================
# ROADMAP
# ==============================================
roadmap:
  # Planning settings
  planning:
    horizon: '4q'              # How far out to plan
    commitment_horizon: '1q'   # What we commit to
    review_frequency: 'monthly'
    
  # Status definitions
  statuses:
    exploring:
      description: 'Under research, not committed'
      color: 'gray'
    planned:
      description: 'In roadmap, not started'
      color: 'blue'
    committed:
      description: 'Resources allocated, will ship'
      color: 'green'
    in_progress:
      description: 'Currently being built'
      color: 'yellow'
    shipped:
      description: 'Released to customers'
      color: 'purple'
    
  # Capacity planning
  capacity:
    quarterly_slots: 3         # Major features per quarter
    buffer_percentage: 20      # Reserve for bugs/urgent

# ==============================================
# COMMUNICATION
# ==============================================
communication:
  # Stakeholder updates
  updates:
    frequency: 'weekly'
    audiences:
      - name: 'engineering'
        focus: ['blockers', 'dependencies', 'upcoming']
        channel: '#engineering'
      - name: 'sales'
        focus: ['customer_facing', 'competitive', 'timelines']
        channel: '#sales'
      - name: 'leadership'
        focus: ['strategic', 'metrics', 'risks']
        channel: 'email'
      - name: 'customer_success'
        focus: ['adoption', 'churn_risk', 'expansion']
        channel: '#customer-success'

  # Request responses
  responses:
    acknowledge_template: 'templates/responses/acknowledge.md'
    decision_template: 'templates/responses/decision.md'
    shipped_template: 'templates/responses/shipped.md'
    decline_template: 'templates/responses/decline.md'

  # Notifications
  notifications:
    on_new_request: true
    on_decision: true
    on_status_change: true
    on_shipped: true
    channels:
      slack: '#product-updates'
      email: 'product-stakeholders@company.com'

# ==============================================
# METRICS & TRACKING
# ==============================================
metrics:
  # Process metrics
  process:
    - name: 'intake_to_decision'
      target: '14d'
      description: 'Time from request to prioritization decision'
    - name: 'decision_to_ship'
      target: '90d'
      description: 'Time from decision to release'
    - name: 'request_resolution_rate'
      target: '70%'
      description: 'Percentage of requests addressed'
    - name: 'stakeholder_satisfaction'
      target: '4.0'
      description: 'Rating from stakeholder surveys (1-5)'

  # Product metrics
  product:
    - name: 'feature_adoption'
      target: '30%'
      window: '90d'
      description: 'Percentage of users using new features'
    - name: 'feature_nps'
      target: '40'
      description: 'NPS for specific features'
    - name: 'time_to_value'
      target: '7d'
      description: 'Days from signup to activation'

  # Intake metrics
  intake:
    track_by_source: true
    track_by_category: true
    track_resolution: true
    report_frequency: 'monthly'

# ==============================================
# INTEGRATIONS
# ==============================================
integrations:
  # Project management
  jira:
    enabled: true
    project: 'PROD'
    issue_types:
      epic: 'Epic'
      story: 'Story'
      task: 'Task'
    custom_fields:
      rice_score: 'customfield_10001'
      priority_tier: 'customfield_10002'
      source: 'customfield_10003'

  # Communication
  slack:
    enabled: true
    workspace: 'company'
    bot_name: 'Peter PM'
    channels:
      intake: '#product-requests'
      updates: '#product-updates'
      internal: '#product-team'

  # Documentation
  notion:
    enabled: false
    workspace: 'company'
    database_id: 'xxx'

  confluence:
    enabled: true
    space: 'PRODUCT'
    parent_page: 'Requirements'

  # Analytics
  analytics:
    enabled: true
    tools:
      - mixpanel
      - amplitude
    auto_import_metrics: true

  # Other agents
  agents:
    thomas:
      enabled: true
      auto_notify_on_ship: true
    tucker:
      enabled: true
      auto_generate_test_plan: true
    chuck:
      enabled: true
      auto_create_release: true

# ==============================================
# WORKFLOWS
# ==============================================
workflows:
  # New request workflow
  new_request:
    steps:
      - action: 'log_request'
        auto: true
      - action: 'acknowledge_requester'
        auto: true
        template: 'acknowledge'
      - action: 'initial_assessment'
        auto: false
        assignee: 'product_manager'
      - action: 'prioritization_decision'
        auto: false
        requires: ['initial_assessment']
      - action: 'communicate_decision'
        auto: true
        template: 'decision'

  # PRD workflow
  prd_workflow:
    steps:
      - action: 'draft_prd'
        status: 'draft'
      - action: 'internal_review'
        status: 'in_review'
        reviewers: ['eng_lead', 'design_lead']
      - action: 'stakeholder_review'
        status: 'stakeholder_review'
        reviewers: ['requesters', 'leadership']
      - action: 'approved'
        status: 'approved'
        next: 'ready_for_development'

  # Feature lifecycle
  feature_lifecycle:
    statuses:
      - 'intake'
      - 'discovery'
      - 'definition'
      - 'prioritized'
      - 'ready_for_design'
      - 'in_design'
      - 'ready_for_dev'
      - 'in_development'
      - 'in_qa'
      - 'ready_for_release'
      - 'released'
      - 'measuring'
