# .maya.yml - Maya Mobile Development Configuration

version: 1

# ==============================================
# PROJECT
# ==============================================
project:
  name: "{{PROJECT_NAME}}"
  bundle_id: "com.company.{{PROJECT_NAME}}"
  version: "1.0.0"
  build_number: 1

# ==============================================
# PLATFORMS
# ==============================================
platforms:
  ios:
    enabled: true
    minimum_version: "15.0"
    target_devices:
      - iphone
      - ipad  # set to false if iPhone-only
    capabilities:
      - push_notifications
      - background_fetch
      - sign_in_with_apple
    
  android:
    enabled: true
    minimum_sdk: 24  # Android 7.0
    target_sdk: 34   # Android 14
    permissions:
      - INTERNET
      - ACCESS_NETWORK_STATE
      - RECEIVE_BOOT_COMPLETED
      - VIBRATE

# ==============================================
# FRAMEWORK
# ==============================================
framework:
  type: react-native  # react-native | flutter | native
  
  react_native:
    version: "0.73"
    new_architecture: true
    expo: false
    
  flutter:
    version: "3.16"
    null_safety: true
    
  native:
    ios:
      language: swift  # swift | objc
      ui_framework: swiftui  # swiftui | uikit
    android:
      language: kotlin  # kotlin | java
      ui_framework: compose  # compose | xml

# ==============================================
# ARCHITECTURE
# ==============================================
architecture:
  pattern: mvvm  # mvvm | mvc | clean | bloc
  
  state_management:
    react_native: zustand  # zustand | redux | mobx | jotai
    flutter: riverpod  # riverpod | bloc | provider | getx
    ios: observable  # observable | combine
    android: stateflow  # stateflow | livedata
    
  navigation:
    react_native: react-navigation
    flutter: go_router
    ios: navigation_stack
    android: navigation_compose

# ==============================================
# NETWORKING
# ==============================================
networking:
  base_url: "https://api.{{PROJECT_NAME}}.com"
  timeout_seconds: 30
  
  retry:
    max_attempts: 3
    backoff: exponential
    
  caching:
    enabled: true
    default_ttl: 3600  # seconds
    
  offline:
    enabled: true
    sync_on_reconnect: true

# ==============================================
# STORAGE
# ==============================================
storage:
  secure_storage:
    enabled: true
    # For tokens, credentials
    
  local_database:
    type: sqlite  # sqlite | realm | hive
    encryption: false
    
  cache:
    images: true
    api_responses: true
    max_size_mb: 100

# ==============================================
# AUTHENTICATION
# ==============================================
authentication:
  methods:
    - email_password
    - apple  # Required for iOS if other social logins
    - google
    
  token_storage: secure_storage
  biometric_enabled: true
  session_timeout_minutes: 30

# ==============================================
# PUSH NOTIFICATIONS
# ==============================================
push_notifications:
  enabled: true
  
  ios:
    provider: apns
    
  android:
    provider: fcm
    
  channels:
    - id: default
      name: Default
      importance: high
    - id: marketing
      name: Marketing
      importance: low

# ==============================================
# ANALYTICS
# ==============================================
analytics:
  providers:
    - firebase
    - mixpanel  # optional
    
  events:
    screen_views: true
    user_actions: true
    errors: true
    performance: true

# ==============================================
# PERFORMANCE
# ==============================================
performance:
  targets:
    cold_start_ms: 2000
    warm_start_ms: 1000
    frame_rate_fps: 60
    api_response_ms: 3000
    
  monitoring:
    enabled: true
    provider: firebase  # firebase | sentry
    
  optimizations:
    image_caching: true
    list_virtualization: true
    lazy_loading: true

# ==============================================
# UI/UX
# ==============================================
ui:
  theme:
    light: true
    dark: true
    system_default: true
    
  touch_targets:
    ios_pt: 44
    android_dp: 48
    
  safe_areas:
    respect_notch: true
    respect_home_indicator: true
    
  haptics:
    enabled: true
    
  animations:
    enabled: true
    respect_reduce_motion: true

# ==============================================
# ACCESSIBILITY
# ==============================================
accessibility:
  minimum_font_scale: 0.8
  maximum_font_scale: 2.0
  voice_over_support: true
  talkback_support: true
  semantic_labels: required

# ==============================================
# TESTING
# ==============================================
testing:
  unit:
    coverage_threshold: 80
    
  integration:
    enabled: true
    
  e2e:
    framework: detox  # detox | maestro | appium
    
  devices:
    ios:
      - "iPhone SE (3rd generation)"
      - "iPhone 15"
      - "iPhone 15 Pro Max"
    android:
      - "Pixel 4a"
      - "Pixel 7"
      - "Galaxy S23"

# ==============================================
# CI/CD
# ==============================================
ci:
  provider: github_actions  # github_actions | bitrise | codemagic
  
  ios:
    signing: automatic  # automatic | manual
    distribution: app_store  # app_store | ad_hoc | enterprise
    
  android:
    signing: release_keystore
    bundle: true  # Use App Bundle
    
  environments:
    development:
      api_url: "https://dev-api.{{PROJECT_NAME}}.com"
    staging:
      api_url: "https://staging-api.{{PROJECT_NAME}}.com"
    production:
      api_url: "https://api.{{PROJECT_NAME}}.com"

# ==============================================
# APP STORE
# ==============================================
app_store:
  ios:
    app_id: "{{APPLE_APP_ID}}"
    team_id: "{{APPLE_TEAM_ID}}"
    
  android:
    package_name: "com.company.{{PROJECT_NAME}}"
    
  metadata:
    primary_category: utilities
    content_rating: "4+"
    
  screenshots:
    ios_sizes:
      - "6.7"  # iPhone 15 Pro Max
      - "6.5"  # iPhone 14 Plus
      - "5.5"  # iPhone 8 Plus
    android_sizes:
      - phone
      - tablet_7
      - tablet_10

# ==============================================
# FEATURE FLAGS
# ==============================================
feature_flags:
  provider: firebase  # firebase | launchdarkly | custom
  
  flags:
    new_onboarding: false
    dark_mode_v2: true
    analytics_v2: false
