# .dexter.yml - Dexter Design Configuration

version: 1

# ==============================================
# BRAND IDENTITY
# ==============================================
brand:
  name: '{{PROJECT_NAME}}'
  logo: '/assets/logo.svg'
  favicon: '/assets/favicon.ico'

# ==============================================
# COLOR SYSTEM
# ==============================================
colors:
  # Primary palette
  primary:
    50: '#EFF6FF'
    100: '#DBEAFE'
    200: '#BFDBFE'
    300: '#93C5FD'
    400: '#60A5FA'
    500: '#3B82F6'
    600: '#2563EB'
    700: '#1D4ED8'
    800: '#1E40AF'
    900: '#1E3A8A'
    DEFAULT: '#3B82F6'
    
  # Neutral/Gray palette
  gray:
    50: '#F9FAFB'
    100: '#F3F4F6'
    200: '#E5E7EB'
    300: '#D1D5DB'
    400: '#9CA3AF'
    500: '#6B7280'
    600: '#4B5563'
    700: '#374151'
    800: '#1F2937'
    900: '#111827'
    950: '#030712'
    
  # Semantic colors
  success:
    light: '#DCFCE7'
    DEFAULT: '#22C55E'
    dark: '#15803D'
    
  warning:
    light: '#FEF3C7'
    DEFAULT: '#F59E0B'
    dark: '#B45309'
    
  error:
    light: '#FEE2E2'
    DEFAULT: '#EF4444'
    dark: '#B91C1C'
    
  info:
    light: '#DBEAFE'
    DEFAULT: '#3B82F6'
    dark: '#1D4ED8'

# ==============================================
# TYPOGRAPHY
# ==============================================
typography:
  # Font families
  fonts:
    sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif']
    mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace']
    
  # Type scale
  scale:
    xs:
      size: '12px'
      lineHeight: '16px'
    sm:
      size: '14px'
      lineHeight: '20px'
    base:
      size: '16px'
      lineHeight: '24px'
    lg:
      size: '18px'
      lineHeight: '28px'
    xl:
      size: '20px'
      lineHeight: '28px'
    2xl:
      size: '24px'
      lineHeight: '32px'
    3xl:
      size: '30px'
      lineHeight: '36px'
    4xl:
      size: '36px'
      lineHeight: '40px'
    5xl:
      size: '48px'
      lineHeight: '1'
      
  # Font weights
  weights:
    normal: 400
    medium: 500
    semibold: 600
    bold: 700

# ==============================================
# SPACING
# ==============================================
spacing:
  # Base unit: 4px
  0: '0px'
  px: '1px'
  0.5: '2px'
  1: '4px'
  1.5: '6px'
  2: '8px'
  2.5: '10px'
  3: '12px'
  4: '16px'
  5: '20px'
  6: '24px'
  8: '32px'
  10: '40px'
  12: '48px'
  16: '64px'
  20: '80px'
  24: '96px'

# ==============================================
# BORDER RADIUS
# ==============================================
radius:
  none: '0px'
  sm: '4px'
  md: '6px'
  DEFAULT: '8px'
  lg: '8px'
  xl: '12px'
  2xl: '16px'
  3xl: '24px'
  full: '9999px'

# ==============================================
# SHADOWS
# ==============================================
shadows:
  none: 'none'
  sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)'
  DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)'
  md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)'
  lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)'
  xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)'
  2xl: '0 25px 50px -12px rgb(0 0 0 / 0.25)'
  inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)'

# ==============================================
# BREAKPOINTS
# ==============================================
breakpoints:
  xs: '0px'
  sm: '480px'
  md: '640px'
  lg: '768px'
  xl: '1024px'
  2xl: '1280px'
  3xl: '1536px'

# ==============================================
# ANIMATION
# ==============================================
animation:
  # Durations
  duration:
    instant: '0ms'
    fast: '150ms'
    normal: '300ms'
    slow: '500ms'
    
  # Easing functions
  easing:
    linear: 'linear'
    in: 'cubic-bezier(0.4, 0, 1, 1)'
    out: 'cubic-bezier(0, 0, 0.2, 1)'
    inOut: 'cubic-bezier(0.4, 0, 0.2, 1)'
    
  # Respect user preferences
  respectReducedMotion: true

# ==============================================
# Z-INDEX
# ==============================================
zIndex:
  hide: -1
  base: 0
  dropdown: 1000
  sticky: 1100
  modal: 1200
  popover: 1300
  tooltip: 1400
  toast: 1500

# ==============================================
# COMPONENTS
# ==============================================
components:
  # Button
  button:
    sizes:
      sm:
        height: '32px'
        padding: '0 12px'
        fontSize: '13px'
      md:
        height: '40px'
        padding: '0 16px'
        fontSize: '14px'
      lg:
        height: '48px'
        padding: '0 20px'
        fontSize: '16px'
    radius: '6px'
    
  # Input
  input:
    sizes:
      sm:
        height: '36px'
        fontSize: '14px'
      md:
        height: '44px'
        fontSize: '16px'
      lg:
        height: '52px'
        fontSize: '18px'
    radius: '6px'
    
  # Card
  card:
    padding:
      compact: '16px'
      default: '24px'
      spacious: '32px'
    radius: '8px'

# ==============================================
# ACCESSIBILITY
# ==============================================
accessibility:
  # WCAG level
  level: 'AA'  # AA or AAA
  
  # Contrast requirements
  contrast:
    normalText: 4.5
    largeText: 3.0
    uiComponents: 3.0
    
  # Touch targets
  touchTarget:
    minimum: '44px'
    recommended: '48px'
    
  # Focus
  focus:
    outlineWidth: '2px'
    outlineOffset: '2px'
    outlineColor: '#3B82F6'

# ==============================================
# PLATFORMS
# ==============================================
platforms:
  web:
    enabled: true
    touchTargetSize: '44px'
    
  ios:
    enabled: true
    touchTargetSize: '44pt'
    safeArea: true
    largeTitle: true
    
  android:
    enabled: true
    touchTargetSize: '48dp'
    materialDesign: 3
    
  desktop:
    enabled: false

# ==============================================
# DESIGN TOKENS OUTPUT
# ==============================================
tokens:
  # Output formats
  output:
    - format: 'css'
      destination: './src/styles/tokens.css'
    - format: 'scss'
      destination: './src/styles/_tokens.scss'
    - format: 'js'
      destination: './src/styles/tokens.js'
    - format: 'json'
      destination: './design-tokens.json'
    - format: 'tailwind'
      destination: './tailwind.tokens.js'

# ==============================================
# ICONS
# ==============================================
icons:
  library: 'lucide'  # lucide | heroicons | phosphor
  defaultSize: '24px'
  sizes:
    sm: '16px'
    md: '20px'
    lg: '24px'
    xl: '32px'
  strokeWidth: 2

# ==============================================
# DARK MODE
# ==============================================
darkMode:
  enabled: true
  default: false  # Start in light mode
  toggle: true    # Allow user toggle
  
  # Color overrides for dark mode
  colors:
    background:
      primary: '#111827'
      secondary: '#1F2937'
      tertiary: '#374151'
    text:
      primary: '#F9FAFB'
      secondary: '#D1D5DB'
      tertiary: '#9CA3AF'
    border:
      primary: '#374151'
      secondary: '#4B5563'
