# .axel.yml - Axel API Design Configuration

version: 1

# ==============================================
# API INFO
# ==============================================
api:
  name: "{{API_NAME}}"
  title: "{{API_TITLE}}"
  version: "1.0.0"
  description: "API for {{DESCRIPTION}}"
  
  servers:
    production:
      url: "https://api.{{DOMAIN}}"
    staging:
      url: "https://api.staging.{{DOMAIN}}"
    development:
      url: "http://localhost:3000"
      
  contact:
    name: "API Support"
    email: "api@{{DOMAIN}}"
    url: "https://docs.{{DOMAIN}}"

# ==============================================
# VERSIONING
# ==============================================
versioning:
  strategy: url_path  # url_path | header | query_param
  current_version: v1
  supported_versions:
    - v1
  deprecation_policy:
    sunset_period_days: 180
    notify_before_days: 90

# ==============================================
# AUTHENTICATION
# ==============================================
authentication:
  methods:
    api_key:
      enabled: true
      header_name: X-API-Key
      prefix: sk_
      environments:
        - prefix: sk_live_
          environment: production
        - prefix: sk_test_
          environment: development
          
    bearer_token:
      enabled: true
      format: jwt
      header: Authorization
      
    oauth2:
      enabled: true
      flows:
        authorization_code:
          authorization_url: "https://auth.{{DOMAIN}}/authorize"
          token_url: "https://auth.{{DOMAIN}}/token"
          scopes:
            read: "Read access"
            write: "Write access"
            admin: "Admin access"
        client_credentials:
          token_url: "https://auth.{{DOMAIN}}/token"

# ==============================================
# RATE LIMITING
# ==============================================
rate_limiting:
  enabled: true
  
  headers:
    limit: X-RateLimit-Limit
    remaining: X-RateLimit-Remaining
    reset: X-RateLimit-Reset
    retry_after: Retry-After
    
  default:
    requests_per_window: 1000
    window_seconds: 3600
    burst: 50
    
  tiers:
    free:
      requests_per_window: 100
      window_seconds: 3600
      burst: 10
      
    starter:
      requests_per_window: 1000
      window_seconds: 3600
      burst: 50
      
    professional:
      requests_per_window: 10000
      window_seconds: 3600
      burst: 200
      
    enterprise:
      requests_per_window: 100000
      window_seconds: 3600
      burst: 1000
      
  endpoint_overrides:
    "POST /search":
      requests_per_window: 100
      window_seconds: 60
    "POST /export":
      requests_per_window: 10
      window_seconds: 3600
    "POST /bulk/*":
      requests_per_window: 5
      window_seconds: 3600

# ==============================================
# PAGINATION
# ==============================================
pagination:
  default_strategy: cursor  # cursor | offset
  
  cursor:
    param_name: cursor
    encode: base64
    
  offset:
    page_param: page
    limit_param: limit
    
  limits:
    default: 20
    min: 1
    max: 100
    
  response_meta:
    include_total: true
    include_links: true

# ==============================================
# ERRORS
# ==============================================
errors:
  format:
    wrapper: error  # Wrap in "error" object
    include_code: true
    include_message: true
    include_request_id: true
    include_documentation_url: true
    include_timestamp: false
    
  validation:
    include_field_errors: true
    field_format:
      - field
      - message
      - code
      
  codes:
    # Map internal errors to API error codes
    authentication_failed: unauthorized
    permission_denied: forbidden
    record_not_found: not_found
    validation_failed: validation_error
    duplicate_record: duplicate
    rate_limit_exceeded: rate_limited

# ==============================================
# WEBHOOKS
# ==============================================
webhooks:
  enabled: true
  
  security:
    algorithm: sha256
    header_signature: X-Webhook-Signature
    header_timestamp: X-Webhook-Timestamp
    timestamp_tolerance_seconds: 300
    
  delivery:
    timeout_seconds: 30
    max_retries: 5
    retry_backoff: exponential
    retry_delays: [0, 300, 1800, 7200, 86400]  # seconds
    
  events:
    # User events
    - user.created
    - user.updated
    - user.deleted
    
    # Order events
    - order.created
    - order.updated
    - order.completed
    - order.cancelled
    
    # Payment events
    - payment.initiated
    - payment.succeeded
    - payment.failed
    - payment.refunded
    
    # Subscription events
    - subscription.created
    - subscription.renewed
    - subscription.cancelled
    - subscription.expired

# ==============================================
# OPENAPI
# ==============================================
openapi:
  version: "3.1.0"
  spec_path: "./openapi/spec.yaml"
  
  generation:
    output_path: "./dist/openapi.yaml"
    include_examples: true
    include_schemas: true
    
  validation:
    strict: true
    require_descriptions: true
    require_examples: true
    require_operation_ids: true
    max_path_depth: 4

# ==============================================
# SDK GENERATION
# ==============================================
sdk:
  output_path: "./sdk"
  
  languages:
    typescript:
      enabled: true
      package_name: "@{{ORG}}/{{API_NAME}}-sdk"
      output: "./sdk/typescript"
      
    python:
      enabled: true
      package_name: "{{API_NAME}}_sdk"
      output: "./sdk/python"
      
    go:
      enabled: true
      module: "github.com/{{ORG}}/{{API_NAME}}-go"
      output: "./sdk/go"
      
    ruby:
      enabled: false
      gem_name: "{{API_NAME}}"
      output: "./sdk/ruby"
      
  features:
    auto_retry: true
    rate_limit_handling: true
    pagination_helpers: true
    webhook_verification: true
    typed_errors: true

# ==============================================
# DOCUMENTATION
# ==============================================
documentation:
  generator: redoc  # redoc | swagger-ui | stoplight
  output_path: "./docs/api"
  
  pages:
    - title: "Getting Started"
      path: "getting-started"
    - title: "Authentication"
      path: "authentication"
    - title: "Rate Limiting"
      path: "rate-limiting"
    - title: "Errors"
      path: "errors"
    - title: "Webhooks"
      path: "webhooks"
    - title: "Changelog"
      path: "changelog"
      
  code_samples:
    languages:
      - curl
      - javascript
      - python
      - go
      - ruby

# ==============================================
# TESTING
# ==============================================
testing:
  contract:
    enabled: true
    spec_path: "./openapi/spec.yaml"
    
  breaking_changes:
    enabled: true
    compare_with: "main"
    
  performance:
    enabled: true
    baseline_response_time_ms: 200
    
  security:
    enabled: true
    checks:
      - authentication_required
      - authorization_enforced
      - input_validation
      - rate_limiting
